### ISSUE TITLE
Backup folder issue

### ISSUE THREAD

**Issue by gergo85** [panakour/oc-backup-plugin#4] opened 2017-12-19 18:38 UTC
When I created a backup, the file is in the "October-CMS" folder instead of "panakour-backup".
I use October build 430.

**Comment by panakour** [comment] 2017-12-19 19:04
Did you change the name inside the config file? I have created too many backups files without this problem using October build 430.

Ps: try again with the latest version and let me know.

**Comment by gergo85** [comment] 2017-12-20 11:24
I use the default settings and the latest version of plugin.

The plugin uses the app name (https://github.com/octobercms/october/blob/master/config/app.php#L31) as a folder name. I do not understand why this is.

**Comment by panakour** [comment] 2017-12-20 12:53
@gergo85 what is your environment?

**Comment by gergo85** [comment] 2017-12-20 13:21
Linux server, PHP 7.0.25

**Comment by panakour** [comment] 2017-12-20 14:00
in a production server or local? if is local, run with docker or virtual machine (vagrant)?

**Comment by gergo85** [comment] 2017-12-20 14:40
I run the website in a production server.

**Comment by panakour** [comment] 2017-12-20 19:11
Are the backups created without any problem?

**Comment by gergo85** [comment] 2017-12-20 21:07
Yes, the backup zip files are fine.

**Comment by panakour** [comment] 2017-12-28 05:38
Unfortunately I can't reproduce this issue, I have tried with various system (ubuntu php7.0.22 - ubuntu php 7.1.5) local and remote and it works as expected.

**Comment by gergo85** [comment] 2017-12-28 23:08
I see. I didn't find the problem.

**Comment by panakour** [comment] 2019-02-15 08:06
Closing as it has been over a year since any activity on this occurred

**Closed as completed by panakour** 2019-02-15 08:06 UTC
